# Generated by Django 4.1.13 on 2025-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_branch_cluster_role_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
    ]
